### ISSUE TITLE
Release of version 1.0.1?

### ISSUE THREAD

**Issue by martinresch** [TobiasDeBruijn/espocrm-java#1]
Hi Tobias,

I just wanted to use the EspoCRM Java client, but in the released version 1.0.0 the dependency `com.github.TheDutchMC:HttpLib` cannot be found on the public Maven repositories. 
In version 1.0.1 the library was removed and `dev.array21:httplib:1.2.2` was introduced.

What are your plans for the release of current version 1.0.1?

Regards
Martin

**Comment by TobiasDeBruijn** [comment]
I can dig into this, thanks for letting me know!

**Comment by TobiasDeBruijn** [comment]
I have released a new version on Maven Central with the correct dependency!
